apiVersion: v1
kind: Secret
metadata:
  name: nr-browser-agent
  namespace: cosmic-coffee
type: Opaque
stringData:
  # These values can be obtained from the NR Browser snippet
  NR_LICENSE_KEY: "CHANGEME"
  NR_ACCOUNT_ID: "CHANGEME"
  NR_TRUST_KEY: "CHANGEME"
  NR_APP_ID: "CHANGEME"
